/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2016-06-25 01:25:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;

public final class datasetManagement_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/E:/PROJECT/RESEARCH/Source/Comparer/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Recommender/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1465637703417L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.0.RELEASE.jar", Long.valueOf(1466303579195L));
    _jspx_dependants.put("jar:file:/E:/PROJECT/RESEARCH/Source/Comparer/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Recommender/WEB-INF/lib/spring-webmvc-4.3.0.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1465522608000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>Quản lý dataset - Recommender</title>\r\n");
      out.write("\r\n");
      out.write("<!-- jquery -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/jquery-2.0.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- bootstrap -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"resources/libs/bootstrap-3.3.6-dist/css/bootstrap.min.css\">\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"resources/libs/bootstrap-3.3.6-dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- bootstrap upload file style -->\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"resources/js/bootstrap-filestyle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- custom css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/main.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- custom query -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/home.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- include header file -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\" style=\"margin: 0 auto;\">\r\n");
      out.write("\t\t\t<div class=\"panel-group\">\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-primary\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\t\tdata-target=\"#panel-content\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"text-uppercase\">Danh sách dataset đã upload</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"panel-content\" class=\"panel-collapse collapse in\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<table class=\"table table-hover\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>STT</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Tên dataset</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Ngày tạo</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Xem thống kê</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>1</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>dataset 1</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>20-6-2016</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><a href=\"#\">Xem thống kê</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>1</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>dataset 2</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>20-6-2016</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><a href=\"#\">Xem thống kê</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>1</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>dataset 3</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>20-6-2016</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><a href=\"#\">Xem thống kê</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-primary\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\t\tdata-target=\"#panel-content2\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"text-uppercase\">Upload datasets</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"panel-content2\" class=\"panel-collapse collapse in\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<form class=\"form\" role=\"form\" action=\"excute\" method=\"post\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tenctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"dataset\">Tên dataset:</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" required=\"required\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"dataset\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"db\">Chọn File Score.txt</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ttype=\"file\" class=\"filestyle form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\trequired=\"required\" data-buttonName=\"btn-primary\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tname=\"file\" data-buttonText=\"Chọn file\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-buttonBefore=\"true\" id=\"score\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"db\">Chọn File Job.txt</label> <input type=\"file\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"filestyle form-control\" data-buttonName=\"btn-primary\" name=\"file\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-buttonText=\"Chọn file\" data-buttonBefore=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tid=\"job\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"db\">Chọn File CV.txt</label> <input type=\"file\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"filestyle form-control\" data-buttonName=\"btn-primary\" name=\"file\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-buttonText=\"Chọn file\" data-buttonBefore=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tid=\"cv\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<br> <input class=\"btn btn-primary\" type=\"submit\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"Upload\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"panel panel-primary\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"panel panel-heading\" data-target=\"#note\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-toggle=\"collapse\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label class=\"text-uppercase\">Lưu ý quan trọng</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"panel-collapse collapse in\" id=\"note\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><p class=\"text-danger\">Để chạy được các thuật\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttoán cần upload đủ 3 file dataset như yêu cầu</p></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><p class=\"text-danger\">Mỗi lần upload dataset\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tmới cần đặt tên khác tên dataset cũ để khỏi bị ghi đè</p></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><p class=\"text-danger\">File upload có định\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdạng là file text (*.txt)</p></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><p class=\"text-danger\">Các cột cách nhau bằng\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tký tự tab (\\t). Các file có thứ tự các cột đúng theo thứ\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttự bên dưới.</p></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><p class=\"text-danger\">File Score.txt gồm:\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tUserId, JobId, Score.</p></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><p class=\"text-danger\">File Job.txt gồm:\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tJobId, JobName, Location, Salary, Category, Requirement,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tTag, Description.</p></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<li><p class=\"text-danger\">File CV.txt gồm:\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tUserId, CVId, UserName, CVName, UserAddress,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tExpectedSalary, Category, Education, Language, Skill,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tCareerObjective.</p></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
